### ISSUE TITLE
Not compatible with 0.13

### ISSUE THREAD

**Issue by ZeroDevOfficial** [byteandahalf/RedstonePlus#1]
java.lang.Exception: The addon com.byteandahalf.rsplus is not compatible with this version of Minecraft PE.
    at com.mojang.minecraftpe.MainActivity.loadNativeAddons(MainActivity.java:1718)
    at com.mojang.minecraftpe.MainActivity.onCreate(MainActivity.java:381)
    at net.zhuoweizhang.mcpelauncher.LauncherAppActivity.onCreate(LauncherAppActivity.java:24)
    at android.app.Activity.performCreate(Activity.java:5958)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
    at android.app.ActivityThread.access$800(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:155)
    at android.app.ActivityThread.main(ActivityThread.java:5696)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by byteandahalf** [comment]
All you need to do is change this line https://github.com/byteandahalf/RedstonePlus/blob/master/AndroidManifest.xml#L18
to say 0.13.0 instead of 0.13.0.b2.
Anyway, I'm not working on this mod anymore, unfortunately.

**Comment by ZeroDevOfficial** [comment]
Ok I fixed that but I have 1 more problem 

java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/com.EpicSteve.RSplus-1/lib/arm/libcom.byteandahalf.rsplus.so" not found
    at java.lang.Runtime.load(Runtime.java:331)
    at java.lang.System.load(System.java:982)
    at com.mojang.minecraftpe.MainActivity.loadNativeAddons(MainActivity.java:1722)
    at com.mojang.minecraftpe.MainActivity.onCreate(MainActivity.java:381)
    at net.zhuoweizhang.mcpelauncher.LauncherAppActivity.onCreate(LauncherAppActivity.java:24)
    at android.app.Activity.performCreate(Activity.java:5958)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
    at android.app.ActivityThread.access$800(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:155)
    at android.app.ActivityThread.main(ActivityThread.java:5696)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by ThePixelGamer** [comment]
Do you have NDK support? And what compiler are you using?
